name: nbconvert

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: python -m pip install jupyter nbconvert matplotlib

    - name: Convert notebook to HTML
      run: jupyter nbconvert --execute --to html --output=index.html test.ipynb

    - name: Commit and push
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add index.html
        git commit -m "Add generated index.html"
        git push
